### ISSUE TITLE
Link to donation after successful registration

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/events.backdropcms.org#37] opened 2023-03-21 19:18 UTC
At the right sidebar of the site, we have this task list:
![image](https://user-images.githubusercontent.com/2423362/226716591-0fd0a974-c03b-48ca-9a32-49e41621e57e.png)

After clicking "Register for the event" and completing the registration, you are shown this:
![image](https://user-images.githubusercontent.com/2423362/226717246-e0c78e36-4d24-446d-88d2-45c83b4a03bd.png)

Leaving the formatting of the fields aside (as well as which ones should be shown here or not), it would really help if we presented the link to donate (which is the nest step in the "Register now" block) in this page. We could add it to a success message, so that it is shown alongside the "Registration received" message.

**Comment by stpaultim** [comment] 2023-09-06 20:56
@jenlampton We're getting quite a few comments about this in Zulip. 

If we can't fix this, we could do something with the design or text to help folks understand.

**Comment by jenlampton** [comment] 2023-09-06 23:14
The redirect to the donation page is not working? I think that's a setting...  checking...

**Comment by jenlampton** [comment] 2023-09-06 23:15
"Confirmation redirect path" is set to `donate`. Setting is correct. I don't know why it's not working.

**Comment by jenlampton** [comment] 2023-09-06 23:17
It worked for me, I was redirected immediately to https://events.backdropcms.org/donate. Closing.

**Comment by stpaultim** [comment] 2023-09-07 05:39
The problem is that the link continues to show without a checkmark after visitors have registered and donated. 

We have had several people comment in Zulip that they are not sure if their registration is complete or if their donation worked, because that link appears to be unfinished. 

By adding checkmarks after the first two items in the list, people are expecting a checkmark after the third. 

I recognize that might be difficult, in which case, can we move this item off the original checklist or somehow add some help text to indicate "Donate (unless you have already)"

I'm not sure, but the problem is that people are confused that step 3 appears incomplete, even after it has been completed. 

![image](https://github.com/backdrop-ops/events.backdropcms.org/assets/3144571/4223e1a0-8a7b-45ea-983b-d98c21869b1a)

**Comment by nattywebdev** [comment] 2023-09-07 07:29
My experience was exactly as described by @stpaultim - left me uncertain about whether my donation had been accepted, and whether my registration was therefore not complete.

**Comment by jenlampton** [comment] 2023-09-07 22:08
> The problem is that the link continues to show without a checkmark after visitors have registered and donated.

That problem is unrelated to the redirect mentioned in this issue -- I think we already have an issue for the checkbox. (closing again)

**Closed by jenlampton** 2023-09-07 22:08 UTC

**Comment by jenlampton** [comment] 2023-09-07 22:14
I couldn't find an existing issue, so @stpaultim  I took your description and created https://github.com/backdrop-ops/events.backdropcms.org/issues/40

**Comment by jenlampton** [comment] 2023-09-14 00:40
Thank you for the donation.

Nothing will change on the events website after making a donation, so you
are almost certainly registered (as long as you completed the registration
form).

We are working on clarifying this in the other issue (linked above).
